### ISSUE TITLE
Typo in BPM localization

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#2043]
See forum topic: https://forum.jmix.ru/t/oshibka-perevoda-modul-bpm-jmix-2-0/1207

**Comment by KartnDev** [comment]
Fixed

**Comment by konyashkina** [comment]
_Tested on
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5366-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)_
Not fixed in 2.0.999-SNAPSHOT

**Comment by KartnDev** [comment]
> _Tested on Jmix version: 2.0.999-SNAPSHOT Jmix Studio plugin version: 2.0.SNAPSHOT5366-231 IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)_ Not fixed in 2.0.999-SNAPSHOT

This problem was produced by not co-committed fix into `release_2_0` branch, now fixed

**Comment by konyashkina** [comment]
Re-tested on
Jmix version: 2.0.999-SNAPSHOT
Passed
